---
# Configuration: https://r-pufky.github.io/docs/service/mkdocs
#
# uv run mkdocs serve --livereload
# uv run mkdocs gh-deploy

###############################################################################
# Page Configuration
###############################################################################
site_name: 'Ansible Development'
repo_url: 'https://github.com/r-pufky/ansible_docs'
site_url: 'https://github.com/r-pufky/ansible_docs'
edit_uri: 'edit/main/docs'
site_author: 'r-pufky'
copyright: '©2025'
remote_branch: 'gh-pages'
remote_name: 'origin'

nav:
  - 'README.md'
  - 'Collections':
      - 'collection/README.md'
      - 'collection/testing.md'
      - 'collection/commit.md'
      - 'collection/release.md'
      - 'collection/troubleshooting.md'
  - 'Roles':
      - 'role/README.md'
      - 'role/best_practices.md'
      - 'role/style_guide.md'
      - 'role/troubleshooting.md'
  - 'Testing':
      - 'Molecule':
          - 'test_environments/molecule/README.md'
          - 'test_environments/molecule/best_practices.md'
          - 'test_environments/molecule/testing.md'
          - 'test_environments/molecule/troubleshooting.md'
      - 'Podman':
          - 'test_environments/podman/README.md'
          - 'test_environments/podman/testing.md'
          - 'test_environments/podman/troubleshooting.md'
      - 'Vagrant':
          - 'test_environments/vagrant/README.md'
          - 'test_environments/vagrant/testing.md'
          - 'test_environments/vagrant/manual_vm.md'
          - 'test_environments/vagrant/troubleshooting.md'
      - 'VirtualBox':
          - 'test_environments/virtualbox/README.md'
          - 'test_environments/virtualbox/troubleshooting.md'
  - 'Docstrings':
      - 'docstring/README.md'
      - 'docstring/unicode.md'
      - 'docstring/task.md'
      - 'docstring/variable.md'
  - 'troubleshooting.md'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/r-pufky'
    - icon: 'material/ansible'
      link: 'https://galaxy.ansible.com/ui/namespaces/r_pufky'
    - icon: 'simple/gnuprivacyguard'
      link: 'https://keys.openpgp.org/vks/v1/by-fingerprint/466EEC2B67516C7117C85CE3A0BC35D16698BAB9'

theme:
  name: 'material'
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: 'material/link'
        name: 'Switch to light mode'
    - media: '(prefers-color-scheme: light)'
      scheme: 'default'
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/toggle-switch'
        name: 'Switch to dark mode'
    - media: '(prefers-color-scheme: dark)'
      scheme: 'slate'
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: 'material/toggle-switch-off'
        name: 'Switch to system preference'
  icon:
    annotation: 'material/chevron-right-circle'
  features:
    - 'navigation.instant'
    - 'navigation.instant.prefetch'
    - 'navigation.instant.progress'
    - 'navigation.tracking'
    - 'navigation.path'
    - 'navigation.indexes'
    - 'navigation.top'
    - 'search.suggest'
    - 'search.highlight'
    - 'toc.follow'
    - 'header.autohide'
    - 'content.action.edit'
    - 'content.footnote.tooltips'
  navigation_depth: 5
  locale: 'en'
  language: 'en'

markdown_extensions:
  - 'attr_list'
  - 'def_list'
  - 'footnotes'
  - 'md_in_html'
  - 'tables'
  - 'pymdownx.betterem'
  - 'pymdownx.magiclink'
  - 'pymdownx.superfences'
  - 'admonition'
  - 'pymdownx.details'
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: 'lower'
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: false
  - 'pymdownx.inlinehilite'

plugins:
  - 'glightbox'
  - git-revision-date-localized:
      enable_creation_date: true
  - 'search'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js'
  - 'https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js'
  - '_material/init.js'

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/vs2015.min.css'
